#pragma once

#define SC_FLOAT double
#define SC_FLOAT_INT __int64
#define SC_FLOAT_PREC_MASK  0x7FFFFFFFFFFFFFF0
#define SC_FLOAT_PREC_BITS(x) (*((SC_FLOAT_INT*) &(x)) & SC_FLOAT_PREC_MASK)
#define SC_FLOAT_PREC_EQL(x, y) (SC_FLOAT_PREC_BITS(x) == SC_FLOAT_PREC_BITS(y))
#define SC_FLOAT_PREC_ZERO(x) (SC_FLOAT_PREC_BITS(x) == 0.0)
